apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fnnfyx71h-python 
  janus-idp.io/tekton: fnnfyx71h-python
  backstage.io/kubernetes-id: fnnfyx71h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fnnfyx71h-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  